# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160222_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('chefs_gestionnaires_du_foyer_group_manage', 'Gérer le groupe des chefs gestionnaires du foyer'),)},
        ),
    ]
