# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160223_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('presidents_group_manage', 'Gérer le groupe des présidents'), ('chefs_gestionnaires_du_foyer_group_manage', 'Gérer le groupe des chefs gestionnaires du foyer'), ('gestionnaires_du_fooyer_group_manage', 'Gérer le groupe des gestionnaires du foyer'))},
        ),
    ]
