# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160415_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/avatars/', verbose_name='Avatar'),
        ),
    ]
