# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 13:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^0[0-9]{9}$', 'Le numéro de téléphone doit être du type 0123456789')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_id',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{6}$', 'Mauvaise forme de numéro de jeton, il ne doit contenir que six chiffres et/ou lettres majuscules')], verbose_name='Numéro de jeton lié'),
        ),
    ]
