# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160322_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
