# Generated by Django 2.1.3 on 2019-01-03 11:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nom')),
                ('module_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Product')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OperatorSaleModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name='Activé')),
                ('delay_post_purchase', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Durée d'affichage du résumé de commande")),
                ('limit_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant limite de commande')),
                ('logout_post_purchase', models.BooleanField(default=False, verbose_name='Deconnexion après une vente')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_operatorsalemodule_shop', to='shops.Shop')),
            ],
            options={
                'permissions': (('use_operatorsalemodule', 'Can use the operator sale module'), ('change_config_operatorsalemodule', 'Can change the config for operator sale module'), ('view_config_operatorsalemodule', 'Can view the config for operator sale module')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SelfSaleModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name='Activé')),
                ('delay_post_purchase', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Durée d'affichage du résumé de commande")),
                ('limit_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant limite de commande')),
                ('logout_post_purchase', models.BooleanField(default=False, verbose_name='Deconnexion après une vente')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_selfsalemodule_shop', to='shops.Shop')),
            ],
            options={
                'permissions': (('use_selfsalemodule', 'Can use the self sale module'), ('change_config_selfsalemodule', 'Can change the config for self sale module'), ('view_config_selfsalemodule', 'Can view the config for self sale module')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(through='modules.CategoryProduct', to='shops.Product'),
        ),
    ]
