# Generated by Django 2.1.10 on 2022-03-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20191120_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorsalemodule',
            name='ask_password',
            field=models.BooleanField(default=False, verbose_name='Demande du mot de passe'),
        ),
    ]
