# Generated by Django 2.1.10 on 2023-09-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_operatorsalemodule_ask_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorsalemodule',
            name='ask_password',
        ),
    ]
