# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('value_type', models.CharField(choices=[('s', 'string'), ('i', 'integer'), ('b', 'boolean')], max_length=1)),
            ],
        ),
    ]
