# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('value', models.CharField(max_length=500, verbose_name='Valeur')),
                ('value_type', models.CharField(choices=[('s', 'string'), ('i', 'integer'), ('f', 'float'), ('b', 'boolean')], max_length=1, verbose_name='Type')),
            ],
        ),
    ]
