# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(max_length=500, verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_type',
            field=models.CharField(choices=[('s', 'string'), ('i', 'integer'), ('f', 'float'), ('b', 'boolean')], max_length=1, verbose_name='Type'),
        ),
    ]
