# Generated by Django 2.1.10 on 2023-09-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_correcting_factor_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='correcting_factor_activated',
        ),
    ]
