# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(max_length=255)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('is_sold', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('list_container', 'Lister les conteneurs'), ('retrieve_container', 'Afficher un conteneur'), ('change_active_keg', "Changer le fut d'une tireuse")),
            },
        ),
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product base name', max_length=255)),
                ('description', models.TextField()),
                ('calculated_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('brand', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('single_product', 'Produit unitaire'), ('container', 'Conteneur')], default='single_product', max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
            ],
            options={
                'permissions': (('list_productbase', 'Lister les produits de base'), ('retrieve_productbase', 'Afficher un produit de base')),
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product unit name', max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(choices=[('CL', 'cl'), ('G', 'g'), ('CENT', 'cent')], default='CL', max_length=255)),
                ('type', models.CharField(choices=[('keg', 'fut'), ('liquor', 'alcool fort'), ('syrup', 'sirop'), ('soft', 'soft'), ('fictional_money', 'fictional money')], default='keg', max_length=255)),
            ],
            options={
                'permissions': (('list_productunit', 'Lister les unités de produits'), ('retrieve_productunit', 'Afficher une unité de produit')),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shop name', max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'permissions': (('reach_workboard_foyer', 'Aller sur le workboard du foyer'),),
            },
        ),
        migrations.CreateModel(
            name='SingleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(max_length=255)),
                ('is_sold', models.BooleanField(default=False)),
                ('product_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_base_single_product', to='shops.ProductBase')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.Sale')),
            ],
            options={
                'permissions': (('list_singleproduct', 'Lister les produits unitaires'), ('retrieve_singleproduct', 'Afficher un produit unitaire')),
            },
        ),
        migrations.CreateModel(
            name='SingleProductFromContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Container')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Sale')),
            ],
        ),
        migrations.AddField(
            model_name='productbase',
            name='product_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_unit', to='shops.ProductUnit'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='container',
            name='product_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_base_container', to='shops.ProductBase'),
        ),
    ]
