# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
        migrations.AlterField(
            model_name='container',
            name='is_empty',
            field=models.BooleanField(default=False),
        ),
    ]
