# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='type',
            field=models.CharField(choices=[('keg', 'fût'), ('liquor', 'alcool fort'), ('syrup', 'sirop'), ('soft', 'soft'), ('food', 'alimentaire'), ('meat', 'viande'), ('cheese', 'fromage'), ('side', 'accompagnement'), ('fictional_money', 'argent fictif')], default='keg', max_length=255, verbose_name='Type'),
        ),
    ]
