# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='type',
            field=models.CharField(choices=[('keg', 'fut'), ('liquor', 'alcool fort'), ('syrup', 'sirop'), ('soft', 'soft'), ('food', 'alimentaire'), ('fictional_money', 'fictional money')], default='keg', max_length=255),
        ),
    ]
