# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproductfromcontainer',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singleproductfromcontainer',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
    ]
