# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='type',
            field=models.CharField(choices=[('keg', 'fut'), ('liquor', 'alcool fort'), ('syrup', 'sirop'), ('soft', 'soft'), ('fictional_money', 'fictional money')], default='keg', max_length=255),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unit',
            field=models.CharField(choices=[('CL', 'cl'), ('G', 'g'), ('CENT', 'cent')], default='CL', max_length=255),
        ),
    ]
