# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='type',
            field=models.CharField(choices=[('keg', 'Fût'), ('soft', 'Soft'), ('alcool fort', 'liquor')], max_length=255),
        ),
    ]
