# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20160502_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
