# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20160222_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbase',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
