# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20160118_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
