# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20160502_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
