# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20160303_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('reach_workboard_foyer', 'Aller sur le workboard du foyer'), ('reach_workboard_auberge', "Aller sur le workboard de l'auberge"), ('sell_auberge', "Vendre des produits à l'auberge"))},
        ),
    ]
