# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20160118_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='localisation',
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
