# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20160222_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
