# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_productbase_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
