# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20160310_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproduct',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
