# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20160118_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='product',
        ),
    ]
