# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20160222_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'permissions': (('can_change_active_keg', "Changer le fut d'une tireuse"),)},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('can_reach_workboard', 'Aller sur le workboard du foyer'),)},
        ),
    ]
