# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_productunit_is_active'),
        ('shops', '0003_auto_20160510_2151'),
    ]

    operations = [
    ]
