# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_container_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='value_when_returnabled',
            new_name='value_when_returned',
        ),
    ]
