# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20160224_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'permissions': (('can_list_container', 'Lister les conteneurs'), ('can_change_active_keg', "Changer le fut d'une tireuse"))},
        ),
        migrations.AlterModelOptions(
            name='productbase',
            options={'permissions': (('can_list_productbase', 'Lister les produits de base'),)},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'permissions': (('can_list_productunit', 'Lister les unités de produits'),)},
        ),
        migrations.AlterModelOptions(
            name='singleproduct',
            options={'permissions': (('can_list_singleproduct', 'Lister les produits unitaires'),)},
        ),
    ]
