# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20160415_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='container',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Est vendu'),
        ),
        migrations.AlterField(
            model_name='container',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Lieu de stockage'),
        ),
        migrations.AlterField(
            model_name='container',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='container',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'achat"),
        ),
        migrations.AlterField(
            model_name='container',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name="Quantité d'unité produit restante"),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Prix calculé'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='description',
            field=models.TextField(default='Description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='name',
            field=models.CharField(default='Product base name', max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name="Quantité d'unité de produit"),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='type',
            field=models.CharField(choices=[('single_product', 'Produit unitaire'), ('container', 'Conteneur')], default='single_product', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='name',
            field=models.CharField(default='Product unit name', max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='type',
            field=models.CharField(choices=[('keg', 'fut'), ('liquor', 'alcool fort'), ('syrup', 'sirop'), ('soft', 'soft'), ('food', 'alimentaire'), ('meat', 'viande'), ('cheese', 'fromage'), ('side', 'accompagnement'), ('fictional_money', 'argent fictif')], default='keg', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unit',
            field=models.CharField(choices=[('CL', 'cl'), ('G', 'g'), ('CENT', 'cent')], default='CL', max_length=255, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(default='Description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(default='Shop name', max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Est vendu'),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Lieu de stockage'),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'achat"),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='singleproductfromcontainer',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name="Quantité d'unité de produit"),
        ),
        migrations.AlterField(
            model_name='singleproductfromcontainer',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Prix de vente'),
        ),
    ]
