# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20160224_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'permissions': (('list_container', 'Lister les conteneurs'), ('change_active_keg', "Changer le fut d'une tireuse"))},
        ),
        migrations.AlterModelOptions(
            name='productbase',
            options={'permissions': (('list_productbase', 'Lister les produits de base'),)},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'permissions': (('list_productunit', 'Lister les unités de produits'),)},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('reach_workboard', 'Aller sur le workboard du foyer'),)},
        ),
        migrations.AlterModelOptions(
            name='singleproduct',
            options={'permissions': (('list_singleproduct', 'Lister les produits unitaires'),)},
        ),
    ]
