# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20160225_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'permissions': (('list_container', 'Lister les conteneurs'), ('retrieve_container', 'Afficher un conteneur'), ('change_active_keg', "Changer le fut d'une tireuse"))},
        ),
        migrations.AlterModelOptions(
            name='productbase',
            options={'permissions': (('list_productbase', 'Lister les produits de base'), ('retrieve_productbase', 'Afficher un produit de base'))},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'permissions': (('list_productunit', 'Lister les unités de produits'), ('retrieve_productunit', 'Afficher une unité de produit'))},
        ),
        migrations.AlterModelOptions(
            name='singleproduct',
            options={'permissions': (('list_singleproduct', 'Lister les produits unitaires'), ('retrieve_singleproduct', 'Afficher un produit unitaire'))},
        ),
    ]
