# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20160118_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
