# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20160225_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('reach_workboard_foyer', 'Aller sur le workboard du foyer'),)},
        ),
    ]
