# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20160118_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='type',
            field=models.CharField(choices=[('fût', 'fût'), ('morceau', 'morceau')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
