# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20160417_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbase',
            name='calculated_price',
        ),
    ]
