# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20160424_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproductfromcontainer',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.Sale'),
        ),
    ]
