# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_tap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tap',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Container'),
        ),
    ]
