# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_auto_20160119_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
