# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 14:22
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_auto_20160425_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='container',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Quantité d'unité produit restante"),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Quantité d'unité de produit"),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='singleproductfromcontainer',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Quantité d'unité de produit"),
        ),
        migrations.AlterField(
            model_name='singleproductfromcontainer',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de vente'),
        ),
    ]
