# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproduct',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.Purchase'),
        ),
    ]
