# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_auto_20160123_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='name',
        ),
        migrations.AddField(
            model_name='productunit',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shops.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productunit',
            name='type',
            field=models.CharField(choices=[('keg', 'Fût'), ('other', 'Autre')], max_length=255),
        ),
    ]
