# Generated by Django 2.1.3 on 2019-01-03 11:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254, verbose_name='Description')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Evenement')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Paiement')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix')),
                ('bills', models.CharField(blank=True, max_length=254, null=True, verbose_name='Facture(s)')),
                ('done', models.BooleanField(default=False, verbose_name='Terminé')),
                ('payment_by_ponderation', models.BooleanField(default=False, verbose_name='Paiement par pondération')),
                ('remark', models.CharField(blank=True, max_length=254, null=True, verbose_name='Remarque')),
                ('allow_self_registeration', models.BooleanField(default=True, verbose_name='Autoriser la self-préinscription')),
                ('date_end_registration', models.DateField(blank=True, null=True, verbose_name='Date de fin de self-préinscription')),
            ],
            options={
                'permissions': (('self_register_event', 'Can self register to an event'), ('proceed_payment_event', 'Can proceed to payment for an event')),
            },
        ),
        migrations.CreateModel(
            name='WeightsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights_registeration', models.IntegerField(default=0)),
                ('weights_participation', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
