# Generated by Django 2.1.10 on 2023-09-08 16:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0003_remove_shop_correcting_factor_activated'),
        ('stocks', '0001_initial'),
    ]

    operations = [
#        migrations.CreateModel(
#            name='BillsEntry',
#            fields=[
#                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
#                ('billname', models.TextField(verbose_name='Bill name')),
#                ('billamount', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant de la facture')),
#                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
#            ],
#        ),
        migrations.AddField(
            model_name='inventory',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='products',
            field=models.ManyToManyField(through='stocks.InventoryProduct', to='shops.Product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.Inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shops.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockentry',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockentry',
            name='products',
            field=models.ManyToManyField(through='stocks.StockEntryProduct', to='shops.Product'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
            preserve_default=False,
        ),
    ]
