# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('cashed', models.BooleanField(default=False)),
                ('date_cash', models.DateField(blank=True, null=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_giver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('date_sign', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('date_cash', models.DateField(blank=True, null=True)),
                ('cashed', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_recipient', to=settings.AUTH_USER_MODEL)),
                ('signatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_signatory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lydia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField(default=django.utils.timezone.now)),
                ('time_operation', models.TimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('cashed', models.BooleanField(default=False)),
                ('date_cash', models.DateField(blank=True, null=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lydia_giver', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lydia_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('foyer', models.FloatField(blank=True, default=0, null=True)),
                ('cashs', models.ManyToManyField(blank=True, to='finances.Cash')),
                ('cheques', models.ManyToManyField(blank=True, to='finances.Cheque')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_client', to=settings.AUTH_USER_MODEL)),
                ('lydias', models.ManyToManyField(blank=True, to='finances.Lydia')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_operator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('validated', models.BooleanField(default=False)),
                ('error_credit', models.BooleanField(default=True)),
                ('cashs', models.ManyToManyField(blank=True, to='finances.Cash')),
                ('cheques', models.ManyToManyField(blank=True, to='finances.Cheque')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_client', to=settings.AUTH_USER_MODEL)),
                ('lydias', models.ManyToManyField(blank=True, to='finances.Lydia')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_operator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
