# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='cashs',
            field=models.ManyToManyField(blank=True, to='finances.Cash'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheques',
            field=models.ManyToManyField(blank=True, to='finances.Cheque'),
        ),
        migrations.AddField(
            model_name='payment',
            name='debit_balance',
            field=models.ManyToManyField(blank=True, to='finances.DebitBalance'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lydias',
            field=models.ManyToManyField(blank=True, to='finances.Lydia'),
        ),
        migrations.AddField(
            model_name='lydia',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lydia_giver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lydia',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lydia_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitbalance',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_debit_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitbalance',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_debit_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='signatory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_signatory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cash',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_giver', to=settings.AUTH_USER_MODEL),
        ),
    ]
