# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 20, 12, 50, 24, 469214)),
        ),
    ]
