# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20160325_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedevent',
            options={'permissions': (('register_sharedevent', "S'inscrire à un événement commun"), ('list_sharedevent', 'Lister les événements communs'))},
        ),
    ]
