# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_sale_is_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account',
            field=models.CharField(max_length=255, verbose_name='Numéro de compte'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(max_length=255, verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_number',
            field=models.CharField(max_length=7, verbose_name='Numéro de chèque'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='is_cashed',
            field=models.BooleanField(default=False, verbose_name='Est encaissé'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='signature_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de signature'),
        ),
        migrations.AlterField(
            model_name='debitbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='debitbalance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='lydia',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='lydia',
            name='banked',
            field=models.BooleanField(default=False, verbose_name='Est encaissé'),
        ),
        migrations.AlterField(
            model_name='lydia',
            name='date_banked',
            field=models.DateField(blank=True, null=True, verbose_name='Date encaissement'),
        ),
        migrations.AlterField(
            model_name='lydia',
            name='date_operation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='lydia',
            name='id_from_lydia',
            field=models.CharField(max_length=255, verbose_name='Numéro unique'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Terminée'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_credit',
            field=models.BooleanField(default=False, verbose_name='Est un crédit'),
        ),
        migrations.AlterField(
            model_name='sharedevent',
            name='bills',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Facture(s)'),
        ),
        migrations.AlterField(
            model_name='sharedevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sharedevent',
            name='description',
            field=models.CharField(max_length=254, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sharedevent',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Terminé'),
        ),
        migrations.AlterField(
            model_name='sharedevent',
            name='ponderation',
            field=models.CharField(default='[]', max_length=10000, verbose_name='Liste ordonnée participants - pondérations'),
        ),
        migrations.AlterField(
            model_name='sharedevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Prix'),
        ),
    ]
