# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 11:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20160220_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lydia',
            name='id_from_lydia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 20, 12, 56, 23, 342051)),
        ),
    ]
