# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20151227_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='lydia',
            name='date_cash',
            field=models.DateField(blank=True, null=True),
        ),
    ]
