# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20160325_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedevent',
            options={'permissions': (('register_sharedevent', "S'inscrire à un événement commun"), ('list_sharedevent', 'Lister les événements communs'), ('manage_sharedevent', 'Gérer les événements communs'))},
        ),
    ]
