# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_lydia_date_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='error_credit',
            field=models.BooleanField(default=True),
        ),
    ]
