# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20160321_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2016, 3, 22, 14, 26, 18, 866231)),
        ),
    ]
