# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20160307_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 19, 33, 50, 364487)),
        ),
    ]
