# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20160307_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 23, 53, 42, 878348)),
        ),
    ]
