# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0004_auto_20160215_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheque',
            old_name='number',
            new_name='cheque_number',
        ),
        migrations.RenameField(
            model_name='cheque',
            old_name='cashed',
            new_name='is_cashed',
        ),
        migrations.RenameField(
            model_name='cheque',
            old_name='date_sign',
            new_name='signature_date',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='date_cash',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='signatory',
        ),
        migrations.AddField(
            model_name='cheque',
            name='account_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='bank',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheque',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
