# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20160322_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2016, 3, 22, 20, 20, 33, 397346)),
        ),
    ]
