# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0004_transaction_error_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('foyer', models.FloatField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('cashs', models.ManyToManyField(blank=True, to='finances.Cash')),
                ('cheques', models.ManyToManyField(blank=True, to='finances.Cheque')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_client', to=settings.AUTH_USER_MODEL)),
                ('lydias', models.ManyToManyField(blank=True, to='finances.Lydia')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_operator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
