# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20160326_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedevent',
            options={'permissions': (('register_sharedevent', "S'inscrire à un événement commun"), ('list_sharedevent', 'Lister les événements communs'), ('manage_sharedevent', 'Gérer les événements communs'), ('proceed_paiement_sharedevent', 'Procéder au paiement des événements communs'))},
        ),
        migrations.AlterField(
            model_name='sharedevent',
            name='ponderation',
            field=models.CharField(default='[]', max_length=10000),
        ),
    ]
