# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0005_auto_20160216_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='bank',
        ),
        migrations.AddField(
            model_name='cheque',
            name='bank_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_bank_account', to='finances.BankAccount'),
            preserve_default=False,
        ),
    ]
