# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20160322_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2016, 3, 23, 19, 16, 53, 835757)),
        ),
    ]
