# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='validated',
        ),
    ]
