# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20160330_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedevent',
            options={'permissions': (('register_sharedevent', "S'inscrire à un événement commun"), ('list_sharedevent', 'Lister les événements communs'), ('manage_sharedevent', 'Gérer les événements communs'), ('proceed_payment_sharedevent', 'Procéder au paiement des événements communs'))},
        ),
    ]
