# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 00:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20160307_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('retrieve_sale', 'Afficher une vente'), ('list_sale', 'Lister les ventes'), ('add_transfert', "Effectuer un transfert d'argent"))},
        ),
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 1, 35, 58, 644858)),
        ),
    ]
