# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20160423_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='signature_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de signature'),
        ),
        migrations.AlterField(
            model_name='debitbalance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='lydia',
            name='date_operation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sharedevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
