# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_auto_20160323_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2016, 3, 24, 12, 14, 24, 302020)),
        ),
    ]
