# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_auto_20160308_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 13, 44, 5, 765733)),
        ),
    ]
