# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_remove_purchase_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='foyer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
