# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_auto_20160423_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.CharField(choices=[('transfert', 'Transfert'), ('recharging', 'Recharging'), ('sale', 'Vente'), ('exceptionnal_movement', 'Mouvement exceptionnel')], default='sale', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='sale',
            name='justification',
            field=models.TextField(blank=True, null=True, verbose_name='Justification'),
        ),
        migrations.AddField(
            model_name='sale',
            name='wording',
            field=models.CharField(default='', max_length=254, verbose_name='Libellé'),
        ),
    ]
