# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0006_auto_20160217_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='operator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='operator_sale', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
