# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20160425_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(choices=[('transfert', 'Transfert'), ('recharging', 'Rechargement'), ('sale', 'Vente'), ('exceptionnal_movement', 'Mouvement exceptionnel')], default='sale', max_length=50, verbose_name='Catégorie'),
        ),
    ]
