# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20160324_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2016, 3, 24, 14, 34, 6, 931739)),
        ),
    ]
