# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20160310_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 15, 45, 22, 989020)),
        ),
    ]
