# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_auto_20160428_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'permissions': (('retrieve_bankaccount', 'Afficher un compte en banque'), ('add_own_bankaccount', 'Ajouter un compte en banque personnel'), ('list_bankaccount', 'Lister les comptes en banque'))},
        ),
    ]
