# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_auto_20160223_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 23, 15, 25, 15, 737560)),
        ),
    ]
