# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_auto_20160324_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='date_operation',
            field=models.DateField(default=datetime.datetime(2016, 3, 24, 18, 29, 7, 109644)),
        ),
    ]
