# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_auto_20160324_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='date_operation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
