# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_auto_20160223_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 24, 21, 14, 13, 298816)),
        ),
    ]
