# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_auto_20160225_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 25, 0, 12, 3, 490451)),
        ),
    ]
