# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0028_auto_20160225_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'permissions': (('retrieve_bankaccount', 'Afficher un compte en banque'), ('list_bankaccount', 'Lister les comptes en banque'))},
        ),
        migrations.AlterModelOptions(
            name='cash',
            options={'permissions': (('retrieve_cash', 'Afficher des espèces'), ('list_cash', 'Lister les espèces'))},
        ),
        migrations.AlterModelOptions(
            name='cheque',
            options={'permissions': (('retrieve_cheque', 'Afficher un cheque'), ('list_cheque', 'Lister les chèques'))},
        ),
        migrations.AlterModelOptions(
            name='lydia',
            options={'permissions': (('retrieve_lydia', 'Afficher un virement Lydia'), ('list_lydia', 'Lister les virements Lydias'))},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('retrieve_sale', 'Afficher une vente'), ('list_sale', 'Lister les ventes'))},
        ),
        migrations.AlterField(
            model_name='lydia',
            name='time_operation',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 25, 19, 41, 26, 279681)),
        ),
    ]
