# Generated by Django 2.1.3 on 2019-01-03 11:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
                ('is_cashed', models.BooleanField(default=False, verbose_name='Est encaissé')),
                ('signature_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de signature')),
                ('cheque_number', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[0-9]{7}$', 'Numéro de chèque\n                                                        invalide')], verbose_name='Numéro de chèque')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ExceptionnalMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Justification')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
                ('is_credit', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Lydia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
                ('date_operation', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('id_from_lydia', models.CharField(max_length=255, verbose_name='Numéro unique')),
                ('is_online', models.BooleanField(default=True, verbose_name='Paiement en ligne')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Recharging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('solution_id', models.PositiveIntegerField()),
            ],
            options={
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Justification')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
            ],
            options={
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
