# Generated by Django 2.1.10 on 2019-09-08 13:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0002_auto_20190103_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
#        migrations.AddField(
#            model_name='exceptionnalmovement',
#            name='operator',
#            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_exceptionnal_movement', to=settings.AUTH_USER_MODEL),
#            preserve_default=False,
#        ),
#        migrations.AddField(
#            model_name='exceptionnalmovement',
#            name='recipient',
#            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_exceptionnal_movement', to=settings.AUTH_USER_MODEL),
#            preserve_default=False,
#        ),
        migrations.AddField(
            model_name='lydia',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais lydia'),
        ),
        migrations.AddField(
            model_name='lydia',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recharging',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operator_recharging', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recharging',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_recharging', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
#        migrations.AddField(
#            model_name='transfert',
#            name='recipient',
#            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_transfert', to=settings.AUTH_USER_MODEL),
#            preserve_default=False,
#        ),
#        migrations.AddField(
#            model_name='transfert',
#            name='sender',
#            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_transfert', to=settings.AUTH_USER_MODEL),
#            preserve_default=False,
#        ),
    ]
