# Generated by Django 2.1.7 on 2019-03-30 15:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20190103_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='lydia',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais lydia'),
        ),
    ]
