# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('notifications', '0002_notificationclass_notificationtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'permissions': (('notification_templates_manage', 'Gérer les template de notification'), ('get_president_notifications', 'Peut recevoir les notifications destinées aux présidents'), ('get_vice-president_notifications', 'Peut recevoir les notifications destinées aux vices-présidents'), ('get_treasurer_notifications', 'Peut recevoir les notifications destinées aux trésoriers'))},
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='category_template',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='message_template',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='type_template',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='target_group_template',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='target_user_template',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='required_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='target_users',
            field=models.CharField(blank=True, choices=[('ACTOR', 'actor'), ('RECIPIENT', 'recipient'), ('USERS_WITH_THE_REQUIRED_PERMISSION', 'users_with_the_required_permission')], max_length=50, null=True),
        ),
    ]
