# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationclass_notificationtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='notification_class',
        ),
        migrations.DeleteModel(
            name='NotificationClass',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
    ]
