# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v1
          
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          pip install setuptools==67.7.1
          pip install -r requirements/dev.txt
          npm add -g less
          cp contrib/development/settings.py borgia/borgia/settings.py
          
      - name: Install dependencies
        run: |
          python borgia/manage.py makemigrations configurations users shops finances events modules sales stocks
          python borgia/manage.py migrate
          python borgia/manage.py loaddata initial
          python borgia/manage.py collectstatic --clear --noinput
          python borgia/manage.py loaddata tests_data
     
      - name: Run tests
        run: python borgia/manage.py test borgia/
      
    
